In [1]:
import numpy as np

# Operaciones con numpy

En este tema vamos aprender como operar matematicamente sobre arrays sin tener que recorrelos. Sin bucles. Esto es uno de los conceptos mas importes de NumPy

In [2]:
examen_matematicas = [3.5, 5, 6.5, 2, 10, 9]
examen_lengua = [6.5, 1, 3, 4, 7, 8]

ex_mat_np = np.array(examen_matematicas)
ex_lng_np = np.array(examen_lengua)

print( (ex_mat_np + ex_lng_np) / 2)


[5.   3.   4.75 3.   8.5  8.5 ]


In [3]:
a = np.array([10,20,30,40,50,60])
b = np.array([2,4,6,8,10,12])

print( 'a + b', a + b )
print( 'a - b', a - b )
print( 'a * b', a * b )
print( 'a / b', a / b )
print( 'a ** 2', a ** 2 )
print( 'b % 3', b % 3 )
print( 'dobles', b * 2 )

a + b [12 24 36 48 60 72]
a - b [ 8 16 24 32 40 48]
a * b [ 20  80 180 320 500 720]
a / b [5. 5. 5. 5. 5. 5.]
a ** 2 [ 100  400  900 1600 2500 3600]
b % 3 [2 1 0 2 1 0]
dobles [ 4  8 12 16 20 24]


## Broadcasting: cuando operamos con elementos de distinta longitud

In [4]:
ap = np.array([ [20,15,60],
                                    [30,45,39.90],
                                    [10,12.90,30],
                                    [20,15.30,60]])

le = np.array([12,3,8.9])

resultado = ap + le
print(resultado)

[[32.  18.  68.9]
 [42.  48.  48.8]
 [22.  15.9 38.9]
 [32.  18.3 68.9]]


## Operaciones de comparacion

Las comparaciones (`>`, `<`, `==`, `!=`, `>=`, `<=`) también se aplican elemento a elemento y devuelven un array de `True`/`False`:

In [5]:
notas = np.array([4,7,6,3,5,10,8,7,9])

# ¿quien aprobaria?
aprobados = notas >= 5
print(notas)
print(aprobados)

# preguntas globales
print('¿Algún alumno suspende?', np.any(notas < 5)) # True
print('¿Todos aprueban?', np.all(notas >= 5)) # False
print('¿Cuanto alumnos aprueban?', np.sum(aprobados)) # True=1 False=0 sum el conteo de 1
print('¿Cuanto alumnos suspende?', np.sum(notas < 5)) 

[ 4  7  6  3  5 10  8  7  9]
[False  True  True False  True  True  True  True  True]
¿Algún alumno suspende? True
¿Todos aprueban? False
¿Cuanto alumnos aprueban? 7
¿Cuanto alumnos suspende? 2


## Funciones especiales => ufuncs

Estamos hablando de operacion, max, min, raiz cuadrada, exponenciales, logaritmicas, sin, cos, redondeos, valores absolutos

In [6]:
numeros = np.array([-2,1.3,0.8,-5.3, 1.0, 7, 29])

# valor absoluto
numeros_abs = np.abs(numeros)
print(numeros_abs)

# exponencial - b^e: Crecimiento de poblaciones, interes compuesto, magnitudes.
# si invierte 1000€ al 5% anual continuo, tres n años tienes: 1000 * e^(0.05*n)

anios = np.array([0,1,5,10,20,40])
capital = np.round(10000 * np.exp(0.02 * anios), 2) 
print(capital)


# logaritmo es la inversa de la exponecial, escala de Richter
# Escala de Ritcher cada grado = 10x energía
# magnitud = log10(energia)

energias = np.array([10, 100, 1000, 10000, 100000, 1000000])
magnitudes = np.log10(energias)
print(magnitudes)
# representacion grafica de magnitudes y energias
for e, m  in zip(energias, magnitudes):
    print(f"Energia: {e} -> Magnitud: {m}")


# raiz cuadrada

resultado = np.sqrt([4,9,16,25,36,49,64,81])
print(resultado)

# redondeos
numeros_racionales = np.array([2.456, 3.6543, 67.234,9.2345,10.345635])

# redondeos matematico
print(np.round(numeros_racionales, 2))
# redondeo a la baja
print(np.floor(numeros_racionales))
# redondeo a la alta
print(np.ceil(numeros_racionales))
# trunc - trunca el numero eliminando parte decimal, siempre hacia cero, equivalente al flor
print(np.trunc(numeros_racionales))




[ 2.   1.3  0.8  5.3  1.   7.  29. ]
[10000.   10202.01 11051.71 12214.03 14918.25 22255.41]
[1. 2. 3. 4. 5. 6.]
Energia: 10 -> Magnitud: 1.0
Energia: 100 -> Magnitud: 2.0
Energia: 1000 -> Magnitud: 3.0
Energia: 10000 -> Magnitud: 4.0
Energia: 100000 -> Magnitud: 5.0
Energia: 1000000 -> Magnitud: 6.0
[2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.46  3.65 67.23  9.23 10.35]
[ 2.  3. 67.  9. 10.]
[ 3.  4. 68. 10. 11.]
[ 2.  3. 67.  9. 10.]


# np.where condicional vectorizado

In [7]:
notas = np.array([4.5, 7.2, 3.1, 8.8, 5.0, 6.3])

"""notas2 = []
for nota in notas:
    if nota >= 5:
        notas2.append('aprobado')
    else:
        notas2.append('suspenso')
print(notas2)"""

print( np.where(notas >= 5, "Aprobado", "Suspenso") )

['Suspenso' 'Aprobado' 'Suspenso' 'Aprobado' 'Aprobado' 'Aprobado']
