# EDA 01 — Análisis de notas de la clase 🎓

**Temas que practicamos:** NumPy 01 al 05 (arrays, creación, propiedades, indexación, operaciones)

---

## Contexto

Eres el profesor de matemáticas de 1º de Bachillerato.  
Tienes las **notas del examen de 25 alumnos** (escala 0–10) y quieres analizarlas con NumPy.

El array ya está preparado para que puedas empezar directamente:

In [1]:
import numpy as np

np.random.seed(42)  # fija la aleatoriedad para obtener siempre los mismos valores
notas = np.round(np.random.uniform(2, 10, size=25), 1)
print("Notas de la clase:", notas)

Notas de la clase: [5.  9.6 7.9 6.8 3.2 3.2 2.5 8.9 6.8 7.7 2.2 9.8 8.7 3.7 3.5 3.5 4.4 6.2
 5.5 4.3 6.9 3.1 4.3 4.9 5.6]


---
## Ejercicio 1 — Conoce tu array

Muestra por pantalla:
- El número total de alumnos
- El tipo de dato del array
- El número de dimensiones

In [2]:
# Tu código aquí
# Número total de alumnos
print("Total de alumnos:", notas.size)

# Tipo de dato del array
print("Tipo de dato:", notas.dtype)

# Número de dimensiones
print("Número de dimensiones:", notas.ndim)

Total de alumnos: 25
Tipo de dato: float64
Número de dimensiones: 1


---
## Ejercicio 2 — Slicing

Muestra las notas del **alumno 5 al alumno 10** (posiciones 4 a 9, recuerda que Python empieza en 0).

In [3]:
# Tu código aquí
print("Notas del alumno 5 al 10:")
print(notas[4:10])

Notas del alumno 5 al 10:
[3.2 3.2 2.5 8.9 6.8 7.7]


---
## Ejercicio 3 — Nota más alta, más baja y media

Calcula con NumPy:
- La nota más alta
- La nota más baja
- La nota media de la clase

> Pista: usa `np.max()`, `np.min()` y `np.mean()`

In [5]:
# Tu código aquí
print("Nota más alta:", np.max(notas))
print("Nota más baja:", np.min(notas))
print("Nota media:", np.mean(notas))

Nota más alta: 9.8
Nota más baja: 2.2
Nota media: 5.528


---
## Ejercicio 4 — Filtrado booleano: aprobados

Crea un array que contenga **solo las notas de los alumnos que han aprobado** (nota >= 5).  
Muestra también cuántos alumnos han aprobado.

In [6]:
# Tu código aquí
aprobados = notas[notas >= 5]

print("Notas aprobadas:")
print(aprobados)

print("Número de aprobados:", aprobados.size)

Notas aprobadas:
[5.  9.6 7.9 6.8 8.9 6.8 7.7 9.8 8.7 6.2 5.5 6.9 5.6]
Número de aprobados: 13


---
## Ejercicio 5 — Operación vectorial: cambio de escala

El director del centro quiere las notas en escala **0–100** (en lugar de 0–10).  
Convierte todo el array multiplicando cada nota por 10.  
Guarda el resultado en una variable llamada `notas_100`.

In [7]:
# Tu código aquí
notas_100 = notas * 10

print(notas_100)

[50. 96. 79. 68. 32. 32. 25. 89. 68. 77. 22. 98. 87. 37. 35. 35. 44. 62.
 55. 43. 69. 31. 43. 49. 56.]


---
## Ejercicio 6 — ¿Cuántos superan la media?

Usando el array original `notas` (escala 0–10), calcula cuántos alumnos tienen una nota **estrictamente superior a la media** de la clase.

In [8]:
# Tu código aquí
media = np.mean(notas)

superan_media = notas > media

print("Media de la clase:", media)
print("Alumnos que superan la media:", np.sum(superan_media))

Media de la clase: 5.528
Alumnos que superan la media: 11


---
## Ejercicio 7 — Suspensos

Crea un array `suspensos` con las notas de los alumnos que NO han aprobado (nota < 5).  
Muestra cuántos son y sus notas.

In [10]:
# Tu código aquí
suspensos = notas[notas < 5]

print("Notas de los suspensos:")
print(suspensos)

print("Número de suspensos:", suspensos.size)

Notas de los suspensos:
[3.2 3.2 2.5 2.2 3.7 3.5 3.5 4.4 4.3 3.1 4.3 4.9]
Número de suspensos: 12


---
## Ejercicio 8 — np.where: etiquetas

Usa `np.where()` para crear un array de texto donde:
- Si nota >= 5 → `"Aprobado"`
- Si nota < 5 → `"Suspenso"`

Muestra el resultado junto a las notas originales.

In [9]:
# Tu código aquí
etiquetas = np.where(notas >= 5, "Aprobado", "Suspenso")

print(etiquetas)

['Aprobado' 'Aprobado' 'Aprobado' 'Aprobado' 'Suspenso' 'Suspenso'
 'Suspenso' 'Aprobado' 'Aprobado' 'Aprobado' 'Suspenso' 'Aprobado'
 'Aprobado' 'Suspenso' 'Suspenso' 'Suspenso' 'Suspenso' 'Aprobado'
 'Aprobado' 'Suspenso' 'Aprobado' 'Suspenso' 'Suspenso' 'Suspenso'
 'Aprobado']
